function [y,H] = filterMIMO(h,x,xlags)

% [y,H] = filterMIMO(h,x,xlags) Apply the MIMO FIR h to input x. x and y
% are [T,Dx]=size(x) and [T,Dy]=size(y); xlags is a vector of length Dx
% with the length of the filter h for each input, and filter h has
% dimensions [sum(xlags),Dy]. H reorganizes h as a cell array of size
% [Dy,Dx]. h is organized as generated by h=inv(Rxx)*Rxy with Rxx and Rxy
% generated by myxcorr(x,y,xlags,1)

% (c) July 9, 2023, Lucas C Parra
%     08/01/2023 transposed H to have size [ydim,xdim]


[T,Dx] = size(x);
Dy = size(h,2);

if length(xlags)==1, xlags = xlags*ones(Dx,1); end

y = zeros(T,Dy);
H = cell(Dy,Dx);

for i=1:Dy
    for j=1:Dx
        H{i,j} = h(sum(xlags(1:j-1))+(1:xlags(j)),i)';
        y(:,i) = y(:,i)+filter(H{i,j},1,x(:,j));
    end 
end
